![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [305]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.26.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [306]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [307]:
# your code goes here
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [308]:
# your code goes here
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [309]:
# your code goes here
X = np.ones((3,2), dtype=np.float64)
print(X)
type(X[0,0])

[[1. 1.]
 [1. 1.]
 [1. 1.]]


numpy.float64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [310]:
X = np.arange(4, dtype=np.int8)

In [311]:
# your code goes here
np.ones_like(X)

array([1, 1, 1, 1], dtype=int8)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [312]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int8)

In [313]:
# your code goes here
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [314]:
# your code goes here
np.ones((4,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [315]:
X = np.array([[2,3], [6,2]], dtype=np.int8)

In [316]:
# your code goes here
np.ones_like(X)*7

array([[7, 7],
       [7, 7]], dtype=int8)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [317]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [318]:
# your code goes here
np.random.randint(1, 11, 3)

array([2, 1, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [319]:
# your code goes here
np.random.random((3,3,3))

array([[[0.64774909, 0.04291659, 0.12643928],
        [0.25712072, 0.67624421, 0.28482927],
        [0.23284865, 0.79727545, 0.7959219 ]],

       [[0.70728089, 0.63201276, 0.18151773],
        [0.36568918, 0.22794253, 0.38865402],
        [0.98104772, 0.15838772, 0.00592951]],

       [[0.60082328, 0.66531618, 0.28943708],
        [0.16375624, 0.24247676, 0.58721123],
        [0.59231669, 0.07452903, 0.6933854 ]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [320]:
# your code goes here
X = [1, 2, 3]
Y = np.array(X)
Y

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [321]:
# your code goes here
X = np.array([1, 2, 3])
Y = X.copy()
print(np.array_equal(X,Y), type(X)==type(Y))

True True


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [322]:
# your code goes here
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [323]:
# your code goes here
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [324]:
# your code goes here
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [325]:
# your code goes here
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [326]:
# your code goes here
Z = np.arange(0, 12).reshape(3,4)
Z.nbytes

96

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [327]:
# your code goes here
X = np.arange(1, 10)
print(X)
X[0]

[1 2 3 4 5 6 7 8 9]


1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [328]:
# your code goes here
X[-1]

9

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [329]:
# your code goes here
X[:3]

array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [330]:
# your code goes here
X[1:-1]

array([2, 3, 4, 5, 6, 7, 8])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [331]:
# your code goes here
X[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [332]:
# your code goes here
X[::2]

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [333]:
# your code goes here
X = np.arange(1, 10).reshape(3,3)
print(X)
X[0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [334]:
# your code goes here
X[-1]

array([7, 8, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [335]:
# your code goes here
X[0,0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [336]:
# your code goes here
X[-1,-1]

9

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [337]:
# your code goes here
X[len(X)//2]

array([4, 5, 6])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [338]:
# your code goes here
X[:2,:2]

array([[1, 2],
       [4, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [339]:
# your code goes here
X[-2:,-2:]

array([[5, 6],
       [8, 9]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [340]:
# your code goes here
X = np.ones((4, 5), dtype=np.int8)
print(type(X[0,0]))
X = X.astype(float)
type(X[0,0])

<class 'numpy.int8'>


numpy.float64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [341]:
# your code goes here
X = np.random.randint(0, 9, 4)
print("forward:", X)
X = X[::-1]
print("reversed:", X)

forward: [1 8 1 1]
reversed: [1 1 8 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [342]:
# your code goes here
X = np.random.randint(0, 11, 5)
print("unsorted:", X)
X.sort()
print("sorted:", X)

unsorted: [0 7 8 5 6]
sorted: [0 5 6 7 8]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [343]:
# your code goes here
X = np.random.randint(0, 11, 5)
print(X)
X[4] = 1
print(X)

[0 3 8 2 6]
[0 3 8 2 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [344]:
X = np.array([30, 40, 50, 40, 50, 60])
# your code goes here
X[X == 50]=40
X

array([30, 40, 40, 40, 40, 60])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [345]:
# your code goes here
X = np.random.randint(1, 11, (3, 3))
print("before:\n", X)
X[-1] = 1
print("after:\n", X)

before:
 [[10  8  3]
 [ 9  9  7]
 [ 6  7  9]]
after:
 [[10  8  3]
 [ 9  9  7]
 [ 1  1  1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [346]:
# your code goes here
X = np.random.randint(1, 11, (3, 3))
print("before:\n", X)
X[-1, -1] = 0
print("after:\n", X)

before:
 [[ 4  9  8]
 [ 6  3  6]
 [ 5 10  9]]
after:
 [[ 4  9  8]
 [ 6  3  6]
 [ 5 10  0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [347]:
# your code goes here
X = np.random.randint(1, 11, (3, 3))
print("before:\n", X)
X += 5
print("after:\n", X)

before:
 [[ 9  1  4]
 [10 10  6]
 [ 5  7 10]]
after:
 [[14  6  9]
 [15 15 11]
 [10 12 15]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [348]:
# your code goes here
X = np.random.randint(-5, 15, 15)
print(X)
mask = X < 0
mask

[12 -4 -5 11 11 10  1 -2  3 14 10  3 11 14 -3]


array([False,  True,  True, False, False, False, False,  True, False,
       False, False, False, False, False,  True])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [349]:
# your code goes here
X[mask]

array([-4, -5, -2, -3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [350]:
# your code goes here
X[X>5]

array([12, 11, 11, 10, 14, 10, 11, 14])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [351]:
# your code goes here
print(X.mean())
X[X>X.mean()]

5.733333333333333


array([12, 11, 11, 10, 14, 10, 11, 14])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [352]:
# your code goes here
X[(X == 2) | (X == 10)]

array([10, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [353]:
X = np.random.randint(-5, 5, 5)
print(X)
# your code goes here
np.all(X != 0)

[-3  4 -1 -1 -3]


True

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [354]:
# your code goes here
np.any(X == 0)

False

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [355]:
# your code goes here
sum(X)

-4

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [356]:
# your code goes here
X.mean()

-0.8

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [357]:
# your code goes here
X = np.eye(3, 4)
print(X)
X.sum(axis=0)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


array([1., 1., 1., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [358]:
# your code goes here
X.mean(axis=1)

array([0.25, 0.25, 0.25])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [359]:
# your code goes here
X.max()

1.0

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)